const returnProducts = () => {
  return [
    {
      id: 1,
      name: "Gaming Laptop",
      category: "Electronics",
      price: 1200,
      quantity: 10,
      image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=600&q=80",
      description: "High-performance laptop with dedicated graphics for seamless gaming and productivity.",
    },
    {
      id: 2,
      name: "Smartphone Pro",
      category: "Electronics",
      price: 900,
      quantity: 15,
      image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80",
      description: "Latest flagship smartphone featuring a stunning display and advanced triple-camera system.",
    },
    {
      id: 3,
      name: "Wireless Headphones",
      category: "Electronics",
      price: 150,
      quantity: 20,
      image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
      description: "Noise-canceling over-ear headphones with 30-hour battery life and premium sound.",
    },
    {
      id: 4,
      name: "Smart Watch",
      category: "Electronics",
      price: 250,
      quantity: 25,
      image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
      description: "Track your fitness, heart rate, and notifications with this sleek, water-resistant smartwatch.",
    },
    {
      id: 5,
      name: "Mechanical Keyboard",
      category: "Electronics",
      price: 120,
      quantity: 12,
      image: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=600&q=80",
      description: "Tactile RGB mechanical keyboard designed for precision typing and fast-paced gaming.",
    },
    {
      id: 6,
      name: "Gaming Mouse",
      category: "Electronics",
      price: 80,
      quantity: 30,
      image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80",
      description: "Ergonomic gaming mouse with adjustable DPI and programmable side buttons.",
    },
    {
      id: 7,
      name: "4K Monitor",
      category: "Electronics",
      price: 400,
      quantity: 8,
      image: "https://images.unsplash.com/photo-1586210579191-33b45e38fa2c?auto=format&fit=crop&w=600&q=80",
      description: "Ultra-high-definition 27-inch monitor with vibrant colors and HDR support.",
    },
    {
      id: 8,
      name: "Bluetooth Speaker",
      category: "Electronics",
      price: 110,
      quantity: 18,
      image: "https://images.unsplash.com/photo-1608156639585-b3a032ef9689?auto=format&fit=crop&w=600&q=80",
      description: "Portable waterproof speaker with deep bass and 360-degree immersive audio.",
    },
    {
      id: 9,
      name: "Men T-Shirt",
      category: "Fashion",
      price: 35,
      quantity: 50,
      image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80",
      description: "Classic cotton crewneck t-shirt, perfect for everyday casual wear.",
    },
    {
      id: 10,
      name: "Women Dress",
      category: "Fashion",
      price: 90,
      quantity: 22,
      image: "https://images.unsplash.com/photo-1539008835279-4346938827c2?auto=format&fit=crop&w=600&q=80",
      description: "Elegant floral summer dress with a comfortable fit and stylish silhouette.",
    },
    {
      id: 11,
      name: "Running Shoes",
      category: "Fashion",
      price: 120,
      quantity: 14,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
      description: "Lightweight, breathable running shoes with superior cushioning and grip.",
    },
    {
      id: 12,
      name: "Leather Jacket",
      category: "Fashion",
      price: 180,
      quantity: 7,
      image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80",
      description: "Premium faux-leather jacket featuring a modern slim-fit design and metal hardware.",
    },
    {
      id: 13,
      name: "Backpack",
      category: "Fashion",
      price: 70,
      quantity: 20,
      image: "https://images.unsplash.com/photo-1553062407-98eeb94c6a62?auto=format&fit=crop&w=600&q=80",
      description: "Durable urban backpack with a padded laptop compartment and water-resistant finish.",
    },
    {
      id: 14,
      name: "Sunglasses",
      category: "Fashion",
      price: 60,
      quantity: 40,
      image: "https://images.unsplash.com/photo-1511499767390-903390e6fbc1?auto=format&fit=crop&w=600&q=80",
      description: "Classic aviator sunglasses with polarized lenses and UV400 protection.",
    },
    {
      id: 15,
      name: "Cap",
      category: "Fashion",
      price: 25,
      quantity: 60,
      image: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=600&q=80",
      description: "Adjustable baseball cap made from 100% breathable cotton.",
    },
    {
      id: 16,
      name: "Handbag",
      category: "Fashion",
      price: 130,
      quantity: 11,
      image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80",
      description: "Sophisticated leather handbag with spacious compartments and a gold-tone finish.",
    },
    {
      id: 17,
      name: "Sofa Set",
      category: "Home",
      price: 900,
      quantity: 4,
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=600&q=80",
      description: "Modern 3-seater sofa with plush velvet upholstery and solid wood legs.",
    },
    {
      id: 18,
      name: "Dining Table",
      category: "Home",
      price: 750,
      quantity: 6,
      image: "https://images.unsplash.com/photo-1530018607912-eff2df114f11?auto=format&fit=crop&w=600&q=80",
      description: "Minimalist oak wood dining table that seats up to six people comfortably.",
    },
    {
      id: 19,
      name: "Office Chair",
      category: "Home",
      price: 200,
      quantity: 15,
      image: "https://images.unsplash.com/photo-1505797149-43b0ad766a69?auto=format&fit=crop&w=600&q=80",
      description: "Ergonomic mesh office chair with lumbar support and adjustable height.",
    },
    {
      id: 20,
      name: "Bed Frame",
      category: "Home",
      price: 600,
      quantity: 5,
      image: "https://images.unsplash.com/photo-1505693419166-419dfc8d5119?auto=format&fit=crop&w=600&q=80",
      description: "King-size upholstered bed frame with a contemporary headboard design.",
    },
    {
      id: 21,
      name: "Table Lamp",
      category: "Home",
      price: 45,
      quantity: 35,
      image: "https://images.unsplash.com/photo-1507473885765-e6ed657f9971?auto=format&fit=crop&w=600&q=80",
      description: "Stylish bedside lamp with a fabric shade and touch-controlled dimming.",
    },
    {
      id: 22,
      name: "Wall Clock",
      category: "Home",
      price: 55,
      quantity: 25,
      image: "https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?auto=format&fit=crop&w=600&q=80",
      description: "Large silent-sweep wall clock with a modern metallic frame.",
    },
    {
      id: 23,
      name: "Curtains",
      category: "Home",
      price: 85,
      quantity: 18,
      image: "https://images.unsplash.com/photo-1514894780063-587428b5a983?auto=format&fit=crop&w=600&q=80",
      description: "Blackout window curtains that offer privacy and thermal insulation.",
    },
    {
      id: 24,
      name: "Carpet",
      category: "Home",
      price: 150,
      quantity: 10,
      image: "https://images.unsplash.com/photo-1534889156217-d34a09b4544c?auto=format&fit=crop&w=600&q=80",
      description: "Soft, hand-woven area rug with a geometric pattern for living room decor.",
    },
    {
      id: 25,
      name: "Football",
      category: "Sports",
      price: 40,
      quantity: 45,
      image: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=600&q=80",
      description: "Professional-grade match ball with superior flight stability and durability.",
    },
    {
      id: 26,
      name: "Cricket Bat",
      category: "Sports",
      price: 110,
      quantity: 12,
      image: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=600&q=80",
      description: "English willow cricket bat with an optimized sweet spot for powerful shots.",
    },
    {
      id: 27,
      name: "Basketball",
      category: "Sports",
      price: 45,
      quantity: 30,
      image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=600&q=80",
      description: "Indoor/outdoor basketball with enhanced grip and consistent bounce.",
    },
    {
      id: 28,
      name: "Tennis Racket",
      category: "Sports",
      price: 130,
      quantity: 14,
      image: "https://images.unsplash.com/photo-1617083934555-563054683002?auto=format&fit=crop&w=600&q=80",
      description: "Lightweight carbon fiber racket designed for better control and swing speed.",
    },
    {
      id: 29,
      name: "Gym Dumbbells",
      category: "Sports",
      price: 90,
      quantity: 20,
      image: "https://images.unsplash.com/photo-1586401100295-7a8096fd231a?auto=format&fit=crop&w=600&q=80",
      description: "Pair of rubber-encased hexagonal dumbbells for a safe and versatile workout.",
    },
    {
      id: 30,
      name: "Yoga Mat",
      category: "Sports",
      price: 35,
      quantity: 40,
      image: "https://images.unsplash.com/photo-1592432676556-26d5630e4202?auto=format&fit=crop&w=600&q=80",
      description: "Extra thick, non-slip yoga mat providing comfort and stability for all poses.",
    },
    {
      id: 31,
      name: "Novel Book",
      category: "Books",
      price: 20,
      quantity: 55,
      image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80",
      description: "A gripping bestseller that explores themes of mystery and adventure.",
    },
    {
      id: 32,
      name: "Science Book",
      category: "Books",
      price: 30,
      quantity: 15,
      image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=600&q=80",
      description: "An illustrated guide to modern physics and the wonders of the cosmos.",
    },
    {
      id: 33,
      name: "History Book",
      category: "Books",
      price: 25,
      quantity: 18,
      image: "https://images.unsplash.com/photo-1535905557558-afc4877a26fc?auto=format&fit=crop&w=600&q=80",
      description: "An in-depth look at major world events that shaped the 20th century.",
    },
    {
      id: 34,
      name: "Notebook",
      category: "Books",
      price: 10,
      quantity: 100,
      image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80",
      description: "Hardcover lined notebook with premium cream-colored paper.",
    },
    {
      id: 35,
      name: "Pen Set",
      category: "Books",
      price: 15,
      quantity: 75,
      image: "https://images.unsplash.com/photo-1585336139118-132f7070a38e?auto=format&fit=crop&w=600&q=80",
      description: "Set of fine-liner pens with archival-quality ink for writing and sketching.",
    },
    {
      id: 36,
      name: "Lipstick",
      category: "Beauty",
      price: 18,
      quantity: 45,
      image: "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?auto=format&fit=crop&w=600&q=80",
      description: "Long-lasting matte lipstick with a hydrating formula and rich pigment.",
    },
    {
      id: 37,
      name: "Perfume",
      category: "Beauty",
      price: 95,
      quantity: 12,
      image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=600&q=80",
      description: "Luxury fragrance with notes of sandalwood, jasmine, and citrus.",
    },
    {
      id: 38,
      name: "Face Cream",
      category: "Beauty",
      price: 40,
      quantity: 28,
      image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=600&q=80",
      description: "Moisturizing face cream enriched with Vitamin E and Hyaluronic acid.",
    },
    {
      id: 39,
      name: "Hair Dryer",
      category: "Beauty",
      price: 75,
      quantity: 15,
      image: "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?auto=format&fit=crop&w=600&q=80",
      description: "Ionic hair dryer with multiple heat settings for fast, frizz-free styling.",
    },
    {
      id: 40,
      name: "Makeup Kit",
      category: "Beauty",
      price: 120,
      quantity: 10,
      image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=600&q=80",
      description: "Professional makeup palette featuring 50 vibrant colors for eyes and face.",
    },
    {
      id: 41,
      name: "Toy Car",
      category: "Kids",
      price: 25,
      quantity: 30,
      image: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format&fit=crop&w=600&q=80",
      description: "Remote-controlled racing car with high-speed tires and rechargeable battery.",
    },
    {
      id: 42,
      name: "Teddy Bear",
      category: "Kids",
      price: 30,
      quantity: 25,
      image: "https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=600&q=80",
      description: "Soft and huggable plush teddy bear made from hypoallergenic materials.",
    },
    {
      id: 43,
      name: "Puzzle Game",
      category: "Kids",
      price: 22,
      quantity: 40,
      image: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=600&q=80",
      description: "1000-piece landscape puzzle designed to improve cognitive skills.",
    },
    {
      id: 44,
      name: "Lego Set",
      category: "Kids",
      price: 85,
      quantity: 15,
      image: "https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?auto=format&fit=crop&w=600&q=80",
      description: "Creative building block set to inspire architectural imagination in children.",
    },
    {
      id: 45,
      name: "School Bag",
      category: "Kids",
      price: 55,
      quantity: 20,
      image: "https://images.unsplash.com/photo-1588072432836-e10032774350?auto=format&fit=crop&w=600&q=80",
      description: "Ergonomic school bag with multiple compartments and reflective safety strips.",
    },
    {
      id: 46,
      name: "Coffee Maker",
      category: "Appliances",
      price: 150,
      quantity: 12,
      image: "https://images.unsplash.com/photo-1520970014086-2208d157c9e2?auto=format&fit=crop&w=600&q=80",
      description: "Programmable drip coffee maker with a thermal carafe and built-in timer.",
    },
    {
      id: 47,
      name: "Blender",
      category: "Appliances",
      price: 90,
      quantity: 18,
      image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=600&q=80",
      description: "High-speed blender perfect for smoothies, soups, and crushing ice.",
    },
    {
      id: 48,
      name: "Microwave Oven",
      category: "Appliances",
      price: 300,
      quantity: 7,
      image: "https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&w=600&q=80",
      description: "Stainless steel microwave with smart sensor cooking and defrost modes.",
    },
    {
      id: 49,
      name: "Refrigerator",
      category: "Appliances",
      price: 1200,
      quantity: 3,
      image: "https://images.unsplash.com/photo-1571175432270-01c2d82597ff?auto=format&fit=crop&w=600&q=80",
      description: "Double-door smart refrigerator with energy-efficient cooling and adjustable shelves.",
    },
    {
      id: 50,
      name: "Air Conditioner",
      category: "Appliances",
      price: 800,
      quantity: 5,
      image: "https://images.unsplash.com/photo-1631541421783-049830588691?auto=format&fit=crop&w=600&q=80",
      description: "Quiet split-system air conditioner with rapid cooling and air purification.",
    },
  ];
};

export default returnProducts;